from enum import Enum 
class TYPES(Enum):
    # SETTERS
    COMM_SET_PARKED =  "COMM_SET_PARKED",
    COMM_SET_UNPARKED = "COMM_SET_UNPARKED",  
    COMM_SET_MOTOR_CONF = "COMM_SET_MOTOR_CONF"
    COMM_SET_BATTERY_CUT = "COMM_SET_BATTERY_CUT"
    # GETTERS 
    COMM_VESC_INFO = "COMM_VESC_INFO",
    COMM_GET_PARKED_STATUS = "COMM_GET_PARKED_STATUS", 
 