from enum import Enum 
class TYPES(Enum):
    COMM_SET_PARKED =  "COMM_SET_PARKED",
    COMM_SET_UNPARKED = "COMM_SET_UNPARKED",
    COMM_GET_PARKED_STATUS = "COMM_GET_PARKED_STATUS",
    COMM_VESC_INFO = "COMM_VESC_INFO",
    COMM_SET_MOTOR_LIMITS = "COMM_SET_MOTOR_LIMITS"
 
